### ISSUE TITLE
v1.310.1 物品分類錯誤

### ISSUE THREAD

**Issue by rChinnnn** [rChinnnn/rchin-poe-trade#1]
3.10 剛改版時有確認物品API提供的各分類道具數量與 3.9 時是一樣的，後來官方有把這季新增的物品加進去。發佈前忘記再次確認這個環節，所以有些物品分類會判斷錯誤

![](https://i.imgur.com/AYHPKQ4.jpg)

**Comment by wlui1125** [comment]
女神的靈縛被誤認為雙手劍

**Comment by rChinnnn** [comment]
@wlui1125 檢查後發現"鯨骨細刃"包含"細刃" ，所以才會誤認XD
謝謝回報 ，我再修改一下判斷基底那塊
