### ISSUE TITLE
statuscode error

### ISSUE THREAD

**Issue by dreamrwolf** [rChinnnn/rchin-poe-trade#104]
I dont know how it work 
please help ，i just cheng3.17to 3.18，some time it work 
sometime error
![image](https://user-images.githubusercontent.com/100653044/170170674-2ef1781e-549f-4177-a9a4-0dac6ec61fa2.png)

**Comment by rChinnnn** [comment]
I have added Error Handling.
Sometime it work, sometime error because of trade API blocking.
