### ISSUE TITLE
请问 搜索出来是这样的是什么原因，以及怎么解决。 非常感谢

### ISSUE THREAD

**Issue by kabanerys** [rChinnnn/rchin-poe-trade#136]
Version: v1.322.3, Server: 國際服
此次搜尋異常！
"<!DOCTYPE html><html lang=\"en-US\"><head><title>Just a moment...</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"><meta name=\"robots\" content=\"noindex,nofollow\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><link href=\"/cdn-cgi/styles/challenges.css\" rel=\"stylesheet\"></head><body class=\"no-js\"><div class=\"main-wrapper\" role=\"main\"><div class=\"main-content\"><noscript><div id=\"challenge-error-title\"><div class=\"h2\"><span class=\"icon-wrapper\"><div class=\"heading-icon warning-icon\"></div></span><span id=\"challenge-error-text\">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: 'www.pathofexile.com',cType: 'managed',cNounce: '70126',cRay: '801dab783cbbfa1a',cHash: 'cba09866b27ceb8',cUPMDTk: \"\\/api\\/trade\\/search\\/Ancestor?__cf_chl_tk=B_PU2mXTXjYnxhTGpo5TyBQt1_Q3oKipcXrO.BOkvWo-1693908494-0-gaNycGzNCuU\",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: \"visitor-time\",fa: \"/api/trade/search/Ancestor?__cf_chl_f_tk=B_PU2mXTXjYnxhTGpo5TyBQt1_Q3oKipcXrO.BOkvWo-1693908494-0-gaNycGzNCuU\",md: \"8.c68970u7NSXrGMUGJ2VSVAa7S2zlk3EXIGlXcbsR4-1693908494-0-AXiWO6qgqsyUPVzzwb5GizvMMfPF7vD7AttfSvXjWoybcMMqlSUPQe8ets6ALVV5oTGJ7_lnGMTfLRJ-S96_KllFUZUc4-lC7MQ6OikJmJ8dcCQ8QQHe_yDT8goEw0pRTE_d49Z7LN6WvmSZ2eZBbzMfPHZzVzb-cNRGVjcdsxRcg7eiQy2hhwDwYJCYlKfsgD4MYm0VkGVbLkaMrnaWT8abS_O3lKxvQ8WR2dLhIeR_WO774iXzOTCvkaFDEYFJ-Hy0qI14WTjIltUnDuJ5DsgEPnOU7bE90iiHZvDNyWnhJeXY8gmupJq9gHSPHAs2mfiK-zgUjYSCN7m_ZxmbRdemWFETwtOFZaPMLoLn0n0wWgkIEKETstzhst0rpjmlFnVTJHlaUXf-K2RhYFGZYR-ujM8xsXOQRxmJRmQLjU70zRLcP3zuDJJgBRUAz-FfI-xcnx750BmHyqljApD9S91M6pnGgQwnlgZ0GUQ1qgSW6fIlSZQFiKLgUlNE9J6W-FuTcJ5cHa3zQBAlHDU0bYwwxRnLYAhHJBVKl52b9qh2qvpNqMyrQtGXAqi4cSlvdIfp8FsAaS-ZgMvmG6BAjj-rjbwjcTAFAAmpWbh2w1XKRAbsAGS-WLillHOi6Cbny9XBIShchsHO-SA4ukDvIxwdBKlLJ-4TK-4kOeV1C0m3ylT2lqSLHfMsT1-DhVc5ywoVq7hbiImsND8GgQPpPKu4OOGkLMnoLgoc-P7RUvX1YzfEShGc7VTWdPuEWkW2RamdqzAezcqYY4_xzoWcJWjKeQtKjloTAxjK8SyYR5btI_-HAN3Sx8YvY8fToqH6H_4ReJ3MImoGeMRRkwj8P8mmycIo9tg3yrEqJhilDnVcVS4g_o1QKoBfSo5wpuiynJJOTU3ZRkaFlcHVSXOTyS5CcxHQbmwEsiVAbOnrx_zw3soBTxGyaBy43tkiyJjv5faYRxGfe_FlETLjX-_DtL9z-IyULmTTcPWwnieTWA4NnEfn3Rnzfl-i2WR4nPSH3oJdGkNgbHMZXHgixRZ4HEsW4dtKkpoZZirAfYIy7eQ3eJCgtF_hOI0ytBt6bHcDYEja9e_qhfW8_IA7JJvMzDvg5ZX7CTQV1Xg5vTZzxuqiR9rWLT9gqM9_VsCoTgljQUtUVA4dyszgDEJOulJ_ige8rA7cD-A0bEyOgrr8t5nZ9KDNCzDKaSPUhmLEIFT-Vu2k2ofbG6ia2IuaT34IR_ZYouDl8S-scO5WCkxl8wXtpKxbBnSD5MUyuCSFjKKbQkGH3J_HqBc9aUS_KBYm7NKPsg4zWXdcEHSw8vffRVhJMC3ViNhEYsT-JaVxtNPyj_9ZYOmnLIUi0cEre3Nh5mMHLG6wnmUc9mhNYMN3EkbwA4spTsiyFrjkhbmxRQYd2wz4c1jrC3d0d7yRMzQt3RoyV10bLmorHOaC9yxUEMYKDld-ZrhRbfq3oxYXJdbsG0VDiO6bvQiTHsh_OMXIEUFE68pNXs_1IWu7Sr-BXvFuem6CoHM6YhbyWYRGAcitz9tVnsTZkhhdDsHkLFw8PhGNLDEcjGbqbXCcqC0gvYEkME_0ns2iwRuTX96dZwa_bdqn2HLk7CxbyhFgJk6WQUx0emNe5HToyC3tznIoyXRXK1I3FtjPzUruvzftP6BwVNkeCbUwaiLYduabhwnT5UZ0vcI5BLRczip62lFwhjWy7dm8_H9M8S16YdH1qLg5dm34aq_ZdM9cH5BsOViz6tvQZmKjL4wARAJY3fsPoTSIaH1zuqaRphcUHo_BWNnlksfAmhpnkFtkHgNk4f3JsBppp_XPOOybPLzp-9_OctFGxI097AeOURG-WI564FUc72aH43fg-38vD3JBkiFQATasf-luhbqRRHj0z1pdUTLbwKJSIrgMVU-woR0lmdu8Aw0_3q3XcAP2Juw_LgWiX6uBvqlwqj9t1ORvVm5W34hYzmAAyudXQFjixqvsP0URBWQl5-9uq-vXA8zhz9JWpkL2IVIuOvLHe0n_vFofqYbkV_yQxOKF3G7kXtVERVs0YDXp5r54j9lutLt84O-2H6hnwQxGrdHeJtPFbYrN5ZirJZCTHlkuks4EHhcAx8N-Pr9Vd9jb29qUoDV-vvz3NtWgpGncjAybc0wqJlOSs173rh9L4j61xRW4ieuAMuQCz1SgdiVGhnvEpushEzFTFKXwNhQD16faGIe6lPiIi4XZjkmhIjKg_JoeqNet8rouLUzW7ozkbYoRz7GHJ56DbvQumWt6bkfvvGp30U9XbMSCQ9PKDiAa6fFmlARkWEd25KjHQ9ArtLSSSlfBnYboI_mZuPUl-TzxGmwLZo7lqvxBSUP4X-oCpHWF_NHAjIF0a4DvCrmLUWpmjMvYEl2T05OGtGGgrU79f1hYMPn5QD_YgF4UkXwBh4jlfY6Cb8pBxfGFcB4SkjD-OGb8jHw8vkb-V660KKL7KSwWY3MKzNN56nGmaecr8UyiGVKmrDyTJUjC9oamougpdEbtwUU4gs3YmSIvf17_iYd54XfY6yJlRKwJ6ARlELOz0vkFWmvGKfCwrP_SgihC8gN7AuzyzaDSoF_UdFua9bbasBoiTgnvNveowGD351aIYYc8lsM3-SBgzFQJPxnj6ALMcD8KJdrDiuk4jzmRNStDeWNk70UheR51enhsAiizbZz-Q57O3C2ybfyIYoQWE-GxcMw0p7bezrqfquhk_Q40d5RC61JB\",cRq: {ru: 'aHR0cHM6Ly93d3cucGF0aG9mZXhpbGUuY29tL2FwaS90cmFkZS9zZWFyY2gvQW5jZXN0b3I=',ra: 'T0F1dGggckNoaW5Qb2VUcmFkZS8xLjMyMi4zIChjb250YWN0OiBiMTAxMjEwMzVAeXVudGVjaC5lZHUudHcp',rm: 'UE9TVA==',d: '3tNb981EvFx0z5xodtGlQZ7rrzKKb843D77+oMeVtzmakt9eOnl0yrvFX/1CTcB3PyT1Q1g97fGjsdGYnp4lEtW8RSc+LI5YEFMWdTrb3Et1RBwEXgnBc8FLqJjhqXBqR9nQsjpf+yE3QzXLHFaVq7Tv0ixzFyALzWgw3MYi2cTnybZMc92V5GVCYCVAC6BJWP1u0ho7mjPl/FLY9/N1T/D+iSmscGJEIzfoPp7YSemUVEchUgHp3/35uBzWHv4uLV6/rsbZ9IqZ0+REpXPDT3xk94cx8xYgLrMl8hEAwze1C0SO7hqKPl7+ibccsmAJORfk/lb8S8yP2bmsZbQOJXbtomB7iZABYCTDX4AIwj450oQfF5gsAaSBOiSM3fbLGojNWlnsuZcjmNIZXEr7rFzn4OYQ1XoZ3C5nZNbtKM0TA7BbRVslfPbN2Ebt9+ooUokpc04L9nr9/k+YaztAKg==',t: 'MTY5MzkwODQ5NC4xMTgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'P6i4wEJSqxTVJxDTGGxUTLb17aFTqKntoW4tQCbqvhU=',i1: 'ntOQNm430vMWh8JTPpOcIw==',i2: 'C+j9x/ML3g4lJcBlYhcf4A==',zh: 'QQ+lpboEqhGP3khoPw6p3Gs9nAQQkOTv/N0CKT6VSv0=',uh: 'ymz7Auv77oXa4Q0rkN4ms6o5mANVaocrSAfVH85ziPQ=',hh: 'FSZhbK/t0tnPDIZtJhu6S3S4VAZv/ixDMUDC4lmYyWs=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=801dab783cbbfa1a';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, \"\\/api\\/trade\\/search\\/Ancestor?__cf_chl_rt_tk=B_PU2mXTXjYnxhTGpo5TyBQt1_Q3oKipcXrO.BOkvWo-1693908494-0-gaNycGzNCuU\" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>"
```
物品種類: 其它
Rarity: 稀有
釋界之邀：塑型
--------
釋界必須見證: 
九頭蛇冰窟, 
牛頭人謎域, 
火鳳凰熔核, 
奇美拉魔坑
--------
物品等級: 83
--------
物品數量詞綴影響事件的總獎勵數量 (implicit)
--------
未鑑定
--------
可以透過個人的地圖裝置來使用此物品，以開啟前往釋界的試煉的傳送門。
```

**Comment by rChinnnn** [comment]
我這幾天邊玩邊用大部分時間都正常，這個應該是伺服器維護中導致的錯誤，待維修完畢就可以正常查詢
