### ISSUE TITLE
Oops! API 串接時似乎發生了一點錯誤... Error: Network Error

### ISSUE THREAD

**Issue by FantasticCHH** [rChinnnn/rchin-poe-trade#137]
小哥您好，不好意思打擾您了。想跟您請教一下
我在操作"HOME"這個function的時候，似乎遇到了一些問題，詢問一下該如何排除此項異常呢?
![image](https://github.com/rChinnnn/rchin-poe-trade/assets/63339132/88b18100-0d19-44b2-a3fe-f5fdaada7b8a)

**Comment by rChinnnn** [comment]
台服似乎有做一些 API 的調整，我這邊將原先從前端發的 API 需求，通通先過一層 local 的後端再發，v1.322.4 應該能解決此問題

**Comment by FantasticCHH** [comment]
感謝您的幫忙，狀況似乎是以解決了。感謝您
