### ISSUE TITLE
建議

### ISSUE THREAD

**Issue by meme755144** [rChinnnn/rchin-poe-trade#16]
1. 建議可以在搜尋黃裝的時候預設將每條詞綴都勾起來，因為會搜尋黃裝基本上就是想要查那些詞的裝的價位.
2. 建議在搜尋傳奇類道具的時候，一樣可以勾選詞綴，因為有時候只需要那條詞的 roll 就可以了.
3. 當在選擇是否為汙染物品時，建議將開關設為三種情形 (都包含、無汙染 與 已汙染).

**Comment by rChinnnn** [comment]
感謝建議！
第 3 點在 v1.312.1 已更新完畢 
第 1.2 點的部分：由於每件物品的詞綴數量都不一定，很容易有廢綴，我在使用上通常會自行判斷並勾選 1~2 條比較有價值的詞綴再搜尋，所以這部分還是先照舊預設不勾選
