### ISSUE TITLE
我在搜尋白色召喚法杖價錢的時候出現這字句

### ISSUE THREAD

**Issue by Fay699** [rChinnnn/rchin-poe-trade#26]
此次搜尋異常，煩請至 巴哈討論串 / Github Issue 回報複製後的物品字串，感謝！
{"error":{"code":2,"message":"Invalid stat domain provided: 每 10 奉獻增加 #% 烙印傷害"}}

之前也搜尋過但是沒問題,可是今天出現了這個

**Comment by rChinnnn** [comment]
目前掌握到這種錯誤的情況應該是
物品稀有度為一般（白裝），丟入倉庫標價後，搜尋標價後的物品就會出錯
預計在下個版本修復完畢，感謝回報！
