### ISSUE TITLE
反馈一个珠宝词缀问题

### ISSUE THREAD

**Issue by zkqixi** [rChinnnn/rchin-poe-trade#27]
珠宝瓦出魔力保留减1后 用查价工具会复制错误 成纪律 减少魔力保留1 @rChinnnn 
![image](https://user-images.githubusercontent.com/55361657/99353326-270b6700-289c-11eb-9f8c-e2b66ebf8a3f.png)

**Comment by rChinnnn** [comment]
感謝回報，這個 bug 在開發分支已修復，下個版本就不會抓錯詞綴了
