### ISSUE TITLE
減少 #% 能力值需求 誤判為 增加 #% 能力值需求

### ISSUE THREAD

**Issue by HARCHHI** [rChinnnn/rchin-poe-trade#5]
As title, copyText is: 
```
稀有度: 稀有
禍害 漫幕
禁禮之靴
--------
閃避值: 136 (augmented)
能量護盾: 26 (augmented)
--------
需求:
等級: 60
敏捷: 42 (augmented)
智慧: 42 (augmented)
--------
插槽: B 
--------
物品等級: 84
--------
減少 18% 能力值需求
增加 37% 閃避與能量護盾
1.7 每秒生命回復
增加 9% 冷卻回復速度
--------
聖戰軍王物品
```

But UI rendering:

![image](https://user-images.githubusercontent.com/6092605/78451920-e0754d80-76ba-11ea-93b1-628614cf6336.png)

**Comment by rChinnnn** [comment]
感謝回報 
檢查 API 後發現能力值需求這條詞只有 "增加" 沒有 "減少"，必須特別處理了
![Postman](https://user-images.githubusercontent.com/14135228/78517132-b9b83380-77ee-11ea-9041-7793d3022d23.png)
但這個 bug 優先程度會放後面一些

**Comment by HARCHHI** [comment]
另外補充一下，看起來目前判斷裝備類型的方式是靠絕對位置判斷的
部分物品會有護盾判斷成鞋子之類的怪異現象
相關的案例改天捕捉到再會報上來

另外我是建議將 詞綴分析/物品分析之類跟框架無關的部分拆成pure funcntion
然後把單元測試建立起來 未來比較好處理(畢竟三個月就要更一次版)
