### ISSUE TITLE
關於附加xx至xx傷害，沒有搜索結果

### ISSUE THREAD

**Issue by amostang** [rChinnnn/rchin-poe-trade#52]
任何物品，只要是 (攻擊類型)附加xx至xx(屬性)傷害 ，都會找不到結果

**Comment by amostang** [comment]
add # to # physical damage (local)  变成 了 pseudo add # to # physical damage

**Comment by rChinnnn** [comment]
抓了幾個物品測試後，應該是武器上的附加傷害這條詞不能用偽屬性查詢，之後修正

**Comment by rChinnnn** [comment]
v1.316.2 已修復
