### ISSUE TITLE
3.17 中文化後查價跳出 "Unknown item base type" / "Unknown item name" Error

### ISSUE THREAD

**Issue by ShanyuenHK** [rChinnnn/rchin-poe-trade#72]
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item base type"}}
```
物品種類: 命運卡(Divination Cards)
Rarity: 命運卡
無痕(No Traces)
--------
堆疊數量: 1 / 9
--------
30x 重鑄石
--------
世界上不存在無法彌補的錯誤。
```

**Comment by ShanyuenHK** [comment]
v1.316.2 正常運作. v1.317.1則會出現搜尋異常{"error":{"code":2,"message":"Unknown item base type"}}

**Comment by rChinnnn** [comment]
這版更新是因應編年史提供的中文化方式更改，請參照步驟更新～ https://poedb.tw/tw/chinese#CommunityWiki

**Comment by rChinnnn** [comment]
似乎有少部分人更新中文化後還是之前的版本(?)，請幫我測試現在遊戲中倉庫是能用英文搜尋嗎？

**Comment by ShanyuenHK** [comment]
以下是使用POE 查價工具 v1.317.1, 沒有使用中文化下的情況:


![image](https://user-images.githubusercontent.com/99357780/153405041-21212499-01fc-4a41-9edc-eb39d5e11649.png)



> 這版更新是因應編年史提供的中文化方式更改（物品資訊內的括弧+英文皆已拿掉），中文化請參照步驟更新～ https://poedb.tw/tw/chinese#CommunityWiki

**Comment by ShanyuenHK** [comment]
倉庫內查詢:

![image](https://user-images.githubusercontent.com/99357780/153405761-522a036f-4b1a-42e1-a883-98ef278ea648.png)

**Comment by ShanyuenHK** [comment]
> 倉庫內查詢:
> 
> ![image](https://user-images.githubusercontent.com/99357780/153405761-522a036f-4b1a-42e1-a883-98ef278ea648.png)

目前暫時的解決方法是使用-v1.316.2

**Comment by ShanyuenHK** [comment]
> > 倉庫內查詢:
> > ![image](https://user-images.githubusercontent.com/99357780/153405761-522a036f-4b1a-42e1-a883-98ef278ea648.png)
> 

目前暫時的解決方法是使用-v1.316.2

**Comment by ShanyuenHK** [comment]
不小心close issue了, 找不到復原的位置..
問題未解決啦

**Comment by rChinnnn** [comment]
@ShanyuenHK 請到 POE 資料夾內點選 PackCheck 把原本的中文化還原，還原後再套用一次最新的中文化試試看
![PackCheck](https://user-images.githubusercontent.com/14135228/153522772-29c3fc47-20a8-4911-92c3-340ee7cbbde0.png)

**Comment by ShanyuenHK** [comment]
請問該下載哪個？

![image](https://user-images.githubusercontent.com/99357780/153543038-ad28c9d8-0000-4fff-8332-8ddbf3bb5922.png)

**Comment by rChinnnn** [comment]
> 請問該下載哪個？
> 
> ![image](https://user-images.githubusercontent.com/99357780/153543038-ad28c9d8-0000-4fff-8332-8ddbf3bb5922.png)

@ShanyuenHK 中文化步驟請參照編年史網頁說明
https://poedb.tw/tw/chinese

**Comment by ShanyuenHK** [comment]
@rChinnnn  今天沒空開電腦，明天才有時間嘗試，不好意思

**Comment by ShanyuenHK** [comment]
> > 請問該下載哪個？
> > ![image](https://user-images.githubusercontent.com/99357780/153543038-ad28c9d8-0000-4fff-8332-8ddbf3bb5922.png)
> 
> @ShanyuenHK 中文化步驟請參照編年史網頁說明 https://poedb.tw/tw/chinese

使用查價工具 v1.317.2, 
使用中文化v3.17.0.1.6,
錯誤已修復，暫時沒有其他問題，可close file, 感謝!

**Comment by ShanyuenHK** [comment]
@rChinnnn 請問PoeChinese3_win.x64.zip 是什麼啦?
