### ISSUE TITLE
傳奇物品和技能珠寶無法查價格

### ISSUE THREAD

**Issue by amostang** [rChinnnn/rchin-poe-trade#74]
直接報錯，無論是裝備還是飾品

**Comment by rChinnnn** [comment]
請幫我隨意查詢幾個物品後，將報錯的資料貼上來～

**Comment by HynnchanC** [comment]
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item name"}}
```
物品種類: 珠寶(Jewels)
Rarity: 傳奇
先祖和諧(Primordial Harmony)
鈷藍珠寶(Cobalt Jewel)
--------
物品等級: 78
--------
魔像技能增加 27% 冷卻回復率
召喚的魔像增加 38% 冷卻時間恢復率
你所召喚的每一種魔像為你的魔像增加 19% 傷害
召喚魔像每秒回復 2% 他們的生命
先祖

**Comment by rChinnnn** [comment]
> 此次搜尋異常！ {"error":{"code":2,"message":"Unknown item name"}}
> 
> ```
> 物品種類: 珠寶(Jewels)
> Rarity: 傳奇
> 先祖和諧(Primordial Harmony)
> 鈷藍珠寶(Cobalt Jewel)
> --------
> 物品等級: 78
> --------
> 魔像技能增加 27% 冷卻回復率
> 召喚的魔像增加 38% 冷卻時間恢復率
> 你所召喚的每一種魔像為你的魔像增加 19% 傷害
> 召喚魔像每秒回復 2% 他們的生命
> 先祖
> ```

@HynnchanC 物品後面還有括弧代表原先套用的中文化沒完全清除，參考這個方式將原先中文化全部還原後再重新套用一次試試 https://github.com/rChinnnn/rchin-poe-trade/issues/72#issuecomment-1035694862

**Comment by kent7834** [comment]
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item name"}}
```
物品種類: 頭部(Helmets)
Rarity: 傳奇
斯塔空加之首(Starkonja's Head)
綢緞之兜(Silken Hood)
--------
閃避值: 812 (augmented)
--------
需求:
等級: 60
敏捷: 138 (unmet)
--------
插槽: G G-G 
--------
物品等級: 83
--------
+52 敏捷
貧血時減少 50% 傷害
增加 10% 攻擊速度
增加 25% 全域暴擊率
增加 120% 閃避值
+100 最大生命
貧血時增加 150% 全域閃避值
--------
斯塔空加死去，並未造就英雄豪傑，
只是永遠長眠冥界。
```
