### ISSUE TITLE
詞綴查詢錯誤

### ISSUE THREAD

**Issue by amostang** [rChinnnn/rchin-poe-trade#79]
增加弓傷害變成增加劍傷害
![error1](https://user-images.githubusercontent.com/37657584/153706697-fda83ba9-31e4-49d6-b614-64ff1b32a31a.PNG)
![error2](https://user-images.githubusercontent.com/37657584/153706699-51a27191-cc8c-41d7-82a8-bdff711cd926.PNG)

**Comment by rChinnnn** [comment]
台服 API 已經有更新這個詞綴資料，目前測試查詢能正常判斷，請再試試看
```
物品種類: 箭袋
稀有度: 稀有
精魂 凌羽
始祖箭袋
--------
需求:
等級: 66
--------
物品等級: 84
--------
攻擊技能增加 30% 元素傷害 (implicit)
--------
攻擊附加 2 至 16 閃電傷害
+302 點命中
+73 最大生命
+35% 火焰抗性
增加 41% 投射物速度
增加 39% 弓技能的傷害

```
