### ISSUE TITLE
搜尋錯誤（不支援搜尋"進階詞綴"）

### ISSUE THREAD

**Issue by wow5109** [rChinnnn/rchin-poe-trade#82]
有看到 #72  問題
我之前的確玩國際服有裝中文化(是載國際服主程式)
但我現在玩的是台版，
出現此錯誤訊息，
另外我已在台版內使用過PackCheck，一樣會有錯誤

Version: v1.317.3
此次搜尋異常！
{"error":{"code":2,"message":"Unknown item name"}}
```
物品種類: 珠寶
Rarity: 傳奇
Conqueror's Efficiency
Crimson Jewel
--------
僅限: 1
--------
物品等級: 1
--------
{ 傳奇詞綴 — 魔力 }
增加 4% 技能的魔力保留效用
{ 傳奇詞綴 — 魔力 }
減少 3% 技能魔力消耗
{ 傳奇詞綴 }
增加 4% 技能效果持續時間
--------
這顆寶石可能也會淌血。
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。
```

**Comment by rChinnnn** [comment]
因為你在複製這個物品時壓到 Alt 鍵了，Ctrl + C + Alt 複製出來的物品訊息會略有不同，目前查價程式並不支援
對著物品按下 Ctrl + C 應該是沒有問題，請再試試

**Comment by wow5109** [comment]
@rChinnnn 我測了好幾遍，我沒有按ALT鍵，也都會出現錯誤耶，
我去用線上鍵盤按鈕測試，我的鍵盤應該是沒問題的

**Comment by wow5109** [comment]
我嘗試把國際服的還原PackCheck也都是不行，
所有物品都不能搜尋

Version: v1.317.3
尚未支援搜尋該道具
```
物品種類: 戒指
Rarity: 稀有
Rune Band
Two-Stone Ring
--------
需求:
等級: 57
--------
物品等級: 82
--------
{ 固定詞綴 — 元素,火焰,閃電,抗性 }
+13(12-16)% 火焰與閃電抗性 (implicit)
--------
{ 前綴 "泛光的"(階層：8) — 防禦 }
+14(13-15) 最大能量護盾
{ 後綴 "電之"(階層：2) — 元素,閃電,抗性 }
+42(42-45)% 閃電抗性
{ 後綴 "熊之"(階層：7) — 能力 }
+22(18-22) 力量
{ 後綴 "豹之"(階層：5) — 能力 }
+30(28-32) 敏捷
```

**Comment by wow5109** [comment]
好吧，我自己找到解決方式了˙，
給有同問題的人參考，

我嘗試解除安裝美版和台版，
都沒有用，
之後試著把
C:\Users\使用者名稱\Documents\My Games
下的Path of Exile整個刪掉，再重開遊戲，就可以了
但其實不用整個砍，
只需要將Path of Exile裡面的 garena_tw_production_Config.ini 砍掉，
重開遊戲，讓他重新建置就可以了˙，
只是你的環境設定都會不見要重設，
建議砍掉之前先備份，
就這樣

**Comment by wow5109** [comment]
@rChinnnn 
後來實測，發現原因是因為，我有改遊戲內按鍵，ctrl和alt相反，造成，
作者有辦法改嗎，雖然看起來消失了˙，
我用幾季了 ，以前互換是沒問題的

**Comment by rChinnnn** [comment]
這個感覺有點難⋯⋯
之前可以用但現在有問題，我猜是遊戲程式本身這次有跟著更新，更改了那塊設定？
由於我是只抓 POE 遊戲內複製出來的字串做分析，太特殊的問題我這邊也不好解

或是你可以關注這邊並試用看看： https://forum.gamer.com.tw/C.php?bsn=18966&snA=130059&tnum=2
有人將 awakened 中文化，國際服能正常運作，台服還在測試中
