### ISSUE TITLE
充能羅盤 "區域含有 #(大師)"、"區域能包含裂痕" 無法搜尋

### ISSUE THREAD

**Issue by zodf0053801** [rChinnnn/rchin-poe-trade#84]
Version: v1.317.3
此次搜尋異常！
{"error":{"code":2,"message":"Invalid stat provided: 使用力量抽取擊殺敵人時有 #% 機率獲得 1 個額外的暴擊球"}}
```
物品種類: 可堆疊通貨
Rarity: 普通
充能的羅盤
--------
物品等級: 60
--------
區域含有瓊恩 (enchant)
剩 3 次使用 (enchant)
--------
右鍵點擊此物品再左鍵點擊虛空石，來套用物品化的六分儀詞綴至虛空石上。
```

**Comment by rChinnnn** [comment]
感謝回報！
這條詞遊戲內敘述方式的跟官方提供的詞綴表有點出入，要額外寫規則去判斷，之後再找時間修復
![Postman](https://user-images.githubusercontent.com/14135228/154876112-74baf39a-8521-4355-853a-6dd45d99494e.png)

**Comment by rChinnnn** [comment]
add issue item

```
物品種類: 可堆疊通貨
稀有度: 普通
充能的羅盤
--------
物品等級: 60
--------
區域能包含裂痕 (enchant)
區域包含額外 1 個裂痕 (enchant)
剩 3 次使用 (enchant)
--------
右鍵點擊此物品再左鍵點擊虛空石，來套用物品化的六分儀詞綴至虛空石上。

```
