### ISSUE TITLE
問題回報: 詞綴查詢錯誤

### ISSUE THREAD

**Issue by httmio** [rChinnnn/rchin-poe-trade#86]
珠寶上的 +#% 法術傷害的暴擊加成 會被判定成 +#%法術傷害

**Comment by rChinnnn** [comment]
我隨意找了台服賣場上有這個詞的珠寶，複製出來後程式是有正確判斷這個詞，請再試試看
```
物品種類: 珠寶
稀有度: 稀有
精魂 之眼
鈷藍珠寶
--------
物品等級: 70
--------
增加 16% 冰冷傷害
+13% 法術傷害的暴擊加成
+16% 閃電技能暴擊加成
增加 12% 敵人冰凍持續時間
5% 機率使用冰冷傷害擊中敵人造成冰凍效果
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。

```
<img width="527" alt="rchin-poe-trade" src="https://user-images.githubusercontent.com/14135228/154898410-2cd0c203-f71b-4731-a1f2-eecd06d670f3.png">
```
物品種類: 珠寶
稀有度: 稀有
魔域 之器
鈷藍珠寶
--------
物品等級: 83
--------
增加 2% 技能的保留效用 (implicit)
增加 7% 非傷害型異常狀態的效果 (implicit)
--------
雙持時 +1% 攻擊傷害格擋率
+13% 法術傷害的暴擊加成
增加 10% 敵人暈眩時間
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。
--------
已汙染

```
<img width="517" alt="rchin-poe-trade" src="https://user-images.githubusercontent.com/14135228/154898488-9d50dc78-ad71-41fa-9a8a-883ef16f215e.png">
```
物品種類: 珠寶
稀有度: 稀有
巨獸希望
鈷藍珠寶
--------
物品等級: 73
--------
雙持時增加 15% 法術傷害 (fractured)
增加 3% 施放速度
+12% 法術傷害的暴擊加成
增加 9% 最大魔力
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。
--------
已汙染
--------
破裂之物

```
<img width="523" alt="rchin-poe-trade" src="https://user-images.githubusercontent.com/14135228/154898658-0c0f0273-6571-445d-aeaa-1fb8122945f9.png">

**Comment by httmio** [comment]
[image: image.png]
[image: image.png]
物品種類: 珠寶
稀有度: 稀有
咒縛明亮
鈷藍珠寶
--------
物品等級: 81
--------
雙持武器時增加 4% 施放速度
增加 9% 全域暴擊率
+14% 法術傷害的暴擊加成
+16% 閃電技能暴擊加成
--------
放置到一個天賦樹的珠寶插槽中以產生效果。右鍵點擊以移出插槽。
--------
備註: ~b/o 1 exalted

目前我珠寶一樣判定有問題，我猜你可能只有單詞? 我猜是在判斷兩詞以上的加成時出了一點BUG，因為我三加成珠寶跟雙詞加成一樣都有這個問題

rChinnnn ***@***.***> 於 2022年2月21日 週一 下午2:08寫道：

**Comment by rChinnnn** [comment]
請幫我確認一下你的查價版本是否為 v1.317.3，這條可能是改過敘述的新詞綴，我這邊最新版是能正常判斷
![rchin-poe-trade_和_問題回報__詞綴查詢錯誤_·_Issue__86_·_rChinnnn_rchin-poe-trade](https://user-images.githubusercontent.com/14135228/155045853-4d288202-1c43-4752-bded-a0f9688930df.png)
